services:
  - type: web
    name: tgs-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 10000
      - key: HOST
        value: "0.0.0.0"
      - key: NODE_ENV
        value: production
      - key: BACKEND_URL
        value: "https://token-system-api.onrender.com"
      - key: NODE_OPTIONS
        value: "--max-http-header-size=16384"
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /*
        name: Access-Control-Allow-Methods
        value: "GET, POST, PUT, DELETE, OPTIONS"
      - path: /*
        name: Access-Control-Allow-Headers
        value: "Origin, X-Requested-With, Content-Type, Accept, Authorization"
      - path: /*
        name: Cache-Control
        value: "no-cache, no-store, must-revalidate"
    autoDeploy: true
    numInstances: 1
    plan: free
    healthCheckPath: /api-status
    sleepApplication: false 