# Render deployment configuration
services:
  - type: web
    name: token-system
    env: node
    buildCommand: npm run render:build
    startCommand: npm run render:start
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: true
    healthCheckPath: /health
    healthCheckPort: 5000  # Explicitly set health check port to 5000 